import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      style={
        {
          "--font-sans": "var(--font-geist-sans)",
        } as React.CSSProperties
      }
    >
      <body className="relative min-h-full overflow-x-hidden bg-background text-foreground">
        <div
          aria-hidden="true"
          className="pointer-events-none fixed inset-0 z-0"
        >
          <div
            className="absolute inset-0"
            style={{
              backgroundImage:
                "radial-gradient(1100px 700px at 8% 18%, rgba(255, 255, 255, 0.65), transparent 62%), radial-gradient(900px 650px at 96% 82%, rgba(226, 226, 226, 0.52), transparent 64%)",
            }}
          />
          <div className="absolute inset-0 backdrop-blur-[2px]" />
          <div
            className="absolute inset-0 bg-repeat opacity-[0.34] mix-blend-multiply"
            style={{
              backgroundImage: "url('/grain-noise.svg')",
              backgroundSize: "190px 190px",
            }}
          />
          <div
            className="absolute inset-0 bg-repeat opacity-[0.15] mix-blend-soft-light"
            style={{
              backgroundImage: "url('/grain-noise.svg')",
              backgroundSize: "130px 130px",
            }}
          />
        </div>

        <div className="relative z-10 flex min-h-full flex-col">
          <div className="relative z-30 mt-4 flex justify-center px-3 sm:px-4 md:px-8 lg:px-14">
            <nav className="flex w-full max-w-5xl flex-col items-center gap-3 rounded-xl border border-border bg-background/95 px-4 py-4 shadow-sm backdrop-blur supports-[backdrop-filter]:bg-background/80 md:grid md:grid-cols-[auto_1fr_auto] md:items-center md:gap-0 md:px-7">
              <h1 className="text-xl font-bold md:text-2xl">UnlockHousing</h1>
              <div className="w-full justify-self-center px-0 md:w-auto md:px-4 lg:px-8">
                <div className="flex flex-wrap items-center justify-center gap-2 md:gap-3">
                  <Link
                    href="/#about"
                    className="inline-flex items-center justify-center px-2 text-sm font-medium text-foreground md:text-base"
                  >
                    About
                  </Link>
                  <Link
                    href="/#insights"
                    className="inline-flex items-center justify-center px-2 text-sm font-medium text-foreground md:text-base"
                  >
                    Insights
                  </Link>
                  <Link
                    href="/#contact"
                    className="inline-flex items-center justify-center px-2 text-sm font-medium text-foreground md:text-base"
                  >
                    Contact
                  </Link>
                </div>
              </div>
              <div className="flex w-full flex-wrap items-center justify-center gap-2 sm:gap-3 md:w-auto md:justify-end">
                <Link
                  href="/auth?mode=signin"
                  className="inline-flex h-10 items-center justify-center rounded-lg border border-border px-3 text-sm font-medium text-foreground transition-colors hover:bg-accent sm:px-4 sm:text-base"
                >
                  Sign In
                </Link>
                <Link
                  href="/auth?mode=signup"
                  className="inline-flex h-10 items-center justify-center rounded-lg border border-transparent bg-foreground px-3 text-sm font-medium text-background transition-colors hover:opacity-90 sm:px-4 sm:text-base"
                >
                  Sign Up
                </Link>
              </div>
            </nav>
          </div>
          {children}
        </div>
      </body>
    </html>
  );
}
